config/routes.rb
Rails.application.routes.draw do

  root 'arguments#controversial'

  resources :arguments, except: [:edit, :update, :destroy] do
    collection do
      get 'controversial'
      get 'popular'
      get 'decided'
      get 'valid'
      get 'invalid'
      get 'active'
      get 'newest'
    end
    resources :signatures, except: [:edit, :update, :destroy]
  end

  resources :addresses

end

app/models/argument.rb
class Argument < ActiveRecord::Base

  extend FriendlyId
  friendly_id :statement, use: :slugged

	has_many :signatures

	has_many :pro_signatures, -> { where negation: false}, class_name: 'Signature'
	has_many :con_signatures, -> { where negation: true}, class_name: 'Signature'


	has_many :pros, -> { uniq }, through: :pro_signatures, class_name: 'BitcoinAddress', source: :bitcoin_address
	has_many :cons, -> { uniq }, through: :con_signatures, class_name: 'BitcoinAddress', source: :bitcoin_address

	def pro_statement
		"I believe that #{statement}"
	end

	def con_statement
		"I doubt that #{statement}"
	end

	def pros_share
		all_sum > 0 ? 1.0*pros_sum/all_sum : nil
	end

	def cons_share
		all_sum > 0 ? 1.0*cons_sum/all_sum : nil
	end

	def update_validity
		self.pros_sum = pros.uniq.sum(&:balance)
		self.cons_sum = cons.uniq.sum(&:balance)
		self.validity = pros_sum - cons_sum
		self.all_sum = pros_sum + cons_sum
		self.min_sum = [pros_sum, cons_sum].min
		save!
	end

end

app/controllers/arguments_controller.rb
class ArgumentsController < ApplicationController
  before_action :set_argument, only: [:show, :edit, :update, :destroy]

  # GET /arguments
  # GET /arguments.json
  def index
    controversial
  end


  def decided
    @arguments = Argument.all.order("abs(validity) desc").page params[:page]
    render :index
  end

  def newest
    @arguments = Argument.all.order("created_at desc").page params[:page]
    render :index
  end

  def active
    @arguments = Argument.all.order("updated_at desc, all_sum desc").page params[:page]
    render :index
  end

  def valid
    @arguments = Argument.all.order("validity desc").page params[:page]
    render :index
  end

  def invalid
    @arguments = Argument.all.order("validity asc").page params[:page]
    render :index
  end

  def popular
    @arguments = Argument.all.order("all_sum desc").page params[:page]
    render :index
  end

  def controversial
    @arguments = Argument.all.order("min_sum desc").page params[:page]
    render :index
  end


  # GET /arguments/1
  # GET /arguments/1.json
  def show
    @is_doubt = !params[:doubt].nil?
  end

  # GET /arguments/new
  def new
    @argument = Argument.new
  end

  # GET /arguments/1/edit
  def edit
  end

  # POST /arguments
  # POST /arguments.json
  def create
    @argument = Argument.new(argument_params.permit(:statement))

    respond_to do |format|
      if @argument.save
        format.html { redirect_to @argument, notice: 'Argument was successfully created.' }
        format.json { render :show, status: :created, location: @argument }
      else
        format.html { render :new }
        format.json { render json: @argument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arguments/1
  # PATCH/PUT /arguments/1.json
  def update
    respond_to do |format|
      if @argument.update(argument_params)
        format.html { redirect_to @argument, notice: 'Argument was successfully updated.' }
        format.json { render :show, status: :ok, location: @argument }
      else
        format.html { render :edit }
        format.json { render json: @argument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arguments/1
  # DELETE /arguments/1.json
  def destroy
    @argument.destroy
    respond_to do |format|
      format.html { redirect_to arguments_url, notice: 'Argument was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_argument
      @argument = Argument.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def argument_params
      params[:argument]
    end
end

app/helpers/arguments_helper.rb
module ArgumentsHelper
end

app/views/arguments/_form.html.slim
= form_for @argument, html: { class: "form form-vertical argument" } do |f|
  .form-group
    p Please keep the statement short and simple, e. g. "God exists".
    p When users vote on it, the prefix "I believe that " or "I doubt that " will be added depending on their choice.
    .controls
      = f.text_field :statement, :class => 'form-control', placeholder: "Your statement"
    = f.error_span(:statement)
  = f.submit "Submit", :class => 'btn btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), arguments_path, :class => 'btn'

app/views/arguments/edit.html.slim
- model_class = Argument
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/arguments/index.html.slim
- model_class = Argument
- title "Vote with your Bitcoin signature"

/ AddThis Button BEGIN
.addthis_toolbox.addthis_default_style.addthis_32x32_style.pull-right addthis:data_track_clickback="false" addthis:data_track_addressbar="false" addthis:ui_language="#{I18n.locale}" addthis:url="http://bitcoinocracy.com"
  a.addthis_button_preferred_1
  a.addthis_button_preferred_2
  a.addthis_button_preferred_3
  a.addthis_button_preferred_4
  a.addthis_button_compact
  a.addthis_counter.addthis_bubble_style
/ AddThis Button END

h1 =t '.title', :default => model_class.model_name.human.pluralize.titleize

.lead Bitcoinocracy offers free and transparent voting mechanism to facilitate decentralized decision making in the Bitcoin ecosystem and to determine the truth backed by real monetary value.

.lead
  = link_to t('.new'), new_argument_path
  |  or check the existing ones:

div role="navigation"
  ul.nav.nav-tabs
    li class="#{action_name=='controversial' ? 'active' : ''}" =link_to "Controversial", controversial_arguments_path
    li class="#{action_name=='popular' ? 'active' : ''}" =link_to "Popular", popular_arguments_path
    li class="#{action_name=='decided' ? 'active' : ''}" =link_to "Decided", decided_arguments_path
    li class="#{action_name=='valid' ? 'active' : ''}" =link_to "Valid", valid_arguments_path
    li class="#{action_name=='invalid' ? 'active' : ''}" =link_to "Invalid", invalid_arguments_path
    li class="#{action_name=='active' ? 'active' : ''}" =link_to "Active", active_arguments_path
    li class="#{action_name=='newest' ? 'active' : ''}" =link_to "Newest", newest_arguments_path

table.table
  - @arguments.each do |argument|
    tr
      td style="text-align:center;"
        div
          = link_to "", "#{argument_path(argument)}", class: "btn btn-xs fa fa-arrow-up", title: "Supported by #{btc_human(argument.pros_sum)}"
        div class="#{argument.validity < 0 ? 'bg-danger' : (argument.validity > 0 ? 'bg-success' : '')}"
          = "#{btc_human(argument.validity,'')}"
        div
          = link_to "", "#{argument_path(argument)}?doubt=1", class: "btn btn-xs fa fa-arrow-down", title: "Opposed by #{btc_human(argument.cons_sum)}"
      td style='vertical-align:middle' 
        = link_to "#{argument.statement}", argument_path(argument), class: "lead"

= paginate @arguments, :theme => 'twitter-bootstrap-3'

app/views/arguments/new.html.slim
- model_class = Argument
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/arguments/show.html.slim
- model_class = Argument
- title @argument.statement
.well
    code
      h1#argument
       = @is_doubt ? @argument.con_statement : @argument.pro_statement

    .row
      .col-md-2
        button.btn.btn-default.btn-lg.btn-info#toggle_button type="button"
          span.fa.fa-refresh aria-hidden="true" 
            |  Doubt

      .col-md-1
        span.lead
          |  OR  
      .col-md-9
        =form_tag(argument_signatures_path(@argument.id), {remote:true, id:"signature_form"}) do |f|
          =text_area("signature", "signature", {style:"font-size:1.5em;width:100%;", placeholder:"Please copy the above statement, sign it with your bitcoin address and paste the signature here", class:"submit_on_edit"})
          =button_tag "Submit", class:"btn btn-lg btn-success pull-right"
          .alert.alert-warning
            | Warning: 
            a href="https://www.reddit.com/r/btc/comments/4mhjh3/psa_bitcoinocracycom_signatures_expose_your/" rel="nofollow" target="_blank" Bitcoin signatures expose your public keys
            |  (that shouldn't be a problem until 
            a href="https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm" rel="nofollow" target="_blank" ECDSA
            |  is broken). Moreover address reuse with a faulty random number generator 
            a href="http://www.nilsschneider.net/2013/01/28/recovering-bitcoin-private-keys.html" rel="nofollow" target="_blank" may leak your private keys
            |.
          =hidden_field("signature", "negation", {value: @is_doubt, autocomplete: false})

    div#signature_status style='display:none'

.row
  .col-md-12
    p 
      h2
        .pull-left
          = model_class.human_attribute_name(:validity) + ': ' + btc_human(@argument.validity)


        / AddThis Button BEGIN
        .addthis_toolbox.addthis_default_style.addthis_32x32_style.pull-right addthis:data_track_clickback="false" addthis:data_track_addressbar="false" addthis:ui_language="#{I18n.locale}"
          a.addthis_button_preferred_1
          a.addthis_button_preferred_2
          a.addthis_button_preferred_3
          a.addthis_button_preferred_4
          a.addthis_button_compact
          a.addthis_counter.addthis_bubble_style
        / AddThis Button END

        small =link_to "see all signatures", argument_path(@argument, :json), class:"btn btn-small btn-link"


.row
    .col-md-6.bg-success
      h3 #{btc_human(@argument.pros_sum)} #{percent_human(@argument.pros_share)} Believe
    .col-md-6.bg-danger
      h3 #{btc_human(@argument.cons_sum)} #{percent_human(@argument.cons_share)} Doubt

.row
    - [@argument.pros, @argument.cons].each_with_index do |addresses, i|
      .col-md-6     
        table class="table #{i==0 ? 'bg-success' : 'bg-danger'}"
          - addresses.each do |address|
            tr
              td
                =link_to address.bitcoin_address, address_path(address.bitcoin_address)
              td
                =btc_human address.balance

input type='hidden' name='pro_statement' id='pro_statement' value=@argument.pro_statement
input type='hidden' name='con_statement' id='con_statement' value=@argument.con_statement

app/views/arguments/show.json.erb
<%= JSON.pretty_generate(
{
  id: @argument.id,
  statement: @argument.statement,
  pros: {
    statement: @argument.pro_statement,
    signatures: @argument.pro_signatures.order('signature').map{|s|
      {
      bitcoin_address: s.bitcoin_address.bitcoin_address,
      signature: s.signature
      }
    }
  },
  cons: {
    statement: @argument.con_statement,
    signatures: @argument.con_signatures.order('signature').map{|s|
      {
      bitcoin_address: s.bitcoin_address.bitcoin_address,
      signature: s.signature
      }
    }
  }
}
).html_safe%>