config/routes.rb
Rails.application.routes.draw do

  root 'arguments#controversial'

  resources :arguments, except: [:edit, :update, :destroy] do
    collection do
      get 'controversial'
      get 'popular'
      get 'decided'
      get 'valid'
      get 'invalid'
      get 'active'
      get 'newest'
    end
    resources :signatures, except: [:edit, :update, :destroy]
  end

  resources :addresses

end

app/views/layouts/application.html.slim
doctype html
html
  head
    / title Bitcoinocracy
    = display_meta_tags site: 'Bitcoinocracy', separator: "&mdash;".html_safe
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = nav_bar static: :top, brand: "Bitcoinocracy", responsive: true
      = menu_group
        = menu_item "Home", root_path
        = menu_item t("arguments.index.new"), new_argument_path
        = menu_item t("addresses.index"), addresses_path

    .container
      - if flash[:error]
        .error.bg-danger =h flash[:error]
      - if flash[:alert]
        .error.bg-danger =h flash[:alert]
      - if flash[:notice]
        .notice.bg-success =h flash[:notice]

      = yield
      .footer
        hr
        a.pull-right href="https://github.com/arsenische/bitcoinocracy/issues/new" target="_blank" Report a bug
        p 
          a href="http://bitcoinocracy.com" Bitcoinocracy.com
          |. Source code is available at 
          a href="https://github.com/arsenische/bitcoinocracy/" target="_blank" GitHub
          |  and you can also 
          a href="https://tip4commit.com/github/arsenische/bitcoinocracy" target="_blank" support
          |  its development.